root: true
overrides:
  - files: "*.js"
    extends:
      - "@socialgouv/eslint-config-recommended"
  - files: "*.ts"
    extends:
      - "@socialgouv/eslint-config-typescript"
    rules:
      "@typescript-eslint/no-invalid-void-type": off
      "import/named": off
      "import/default": off
      "import/no-named-as-default": off
